### ISSUE TITLE
pairs of list

### ISSUE THREAD

**Issue by zteitler** [Macaulay2/M2#208]
Something like this would add a bit of orthogonality:

    i13 : pairs {a,b,c,d}
    stdio:13:1:(3): error: expected a hash table or a raw polynomial

    i12 : pairs List := x -> apply(#x, i -> (i,x#i));

from: bugs/dan/0-pairs-of-list

**Comment by zteitler** [comment]
Ah, I made a mistake in this. Bad commit, sorry. I'm fixing it right now---it is taking a little bit of time to check things carefully (I don't want to make *another* mistake).

(The documentation key (pairs, BasicList) didn't match the contents of the documentation node, and also there needs to be a method installed. Those changes should have happened at the same time as putting in the documentation key. I didn't check before committing. Well, they are fixed on my computer & I'm building M2 right now. If it builds and the documentation is okay then you will see one more commit here.)

**Comment by DanGrayson** [comment]
I'm already fixing it, Zach...

**Comment by DanGrayson** [comment]
See
https://github.com/Macaulay2/M2/commit/a1ff04ac15b99e9790df0016fd5f97f294959c11
for my
changes, which partially fixed things.

**Comment by zteitler** [comment]
Okay!
